BBMASK .= "|meta-rdk/recipes-extended/crashupload/"
BBMASK .= "|meta-rdk/recipes-extended/mediaframework/"
BBMASK .= "|meta-rdk/recipes-qt/"
BBMASK .= "|meta-rdk/recipes-rdkb/ruli"
BBMASK .= "|meta-rdk/recipes-ccsp/ccsp/ccsp-moca.bb"

BBMASK .= "|meta-cmf-comcast/recipes-extended/iarmmgrs/"
BBMASK .= "|meta-cmf-comcast/recipes-extended/mediaframework/"
BBMASK .= "|meta-cmf-comcast/recipes-extended/mediastreamer/"
BBMASK .= "|meta-cmf-comcast/recipes-extended/tdk/"
BBMASK .= "|meta-cmf-comcast/recipes-multimedia/gstreamer/"
BBMASK .= "|meta-cmf-comcast/recipes-thirdparty/tr69/"

BBMASK .= "|meta-cmf-raspberrypi/recipes-extended/gstqamtunersrc/"
BBMASK .= "|meta-cmf-raspberrypi/recipes-extended/devicesettings/"
BBMASK .= "|meta-cmf-raspberrypi/recipes-extended/dvrmgr/dvrmgr-hal-noop_git.bb"

BBMASK .= "|meta-cmf/recipes-devtools/cunit"
